// import { Inter } from "@next/font/google";
import Head from "next/head";
import LayoutMain from "../components/layout/LayoutMain";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Couresy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <LayoutMain></LayoutMain> */}
    </>
  );
}
